import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../components/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>codeSplit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar user={{name: 'Flavio Alexandre'}} theme='light'/>

    </div>
  )
}

export default Home
